{ inputs, config, lib, pkgs, ... }:

{
  home.packages = with pkgs; [
    brightnessctl
    inotify-tools
  ];
  
  imports = [
    inputs.noctalia.homeModules.default
  ];

  # Changes made in Noctalia settings UI will update a file in 
  # ~/.local/state/noctalia/settings.toml 
  # .. and merge it with config toml file generated by this module, 
  # causing config drift. 
  # The following prevents this by deleting the state file on rebuild
  # however it the change is only applied after noctalia restart.
  # Because of that, the file will most of the time be empty. Use this
  # to easily identify which option was changed and then add it to this module.
  home.activation.resetNoctaliaState = lib.hm.dag.entryAfter ["writeBoundary"] ''
    STATE_DIR="${config.home.homeDirectory}/.local/state/noctalia"
    STATE_FILE="$STATE_DIR/settings.toml"
    
    # Remove the state file if it exists
    if [ -f "$STATE_FILE" ]; then
      rm -f "$STATE_FILE"
    fi
    
    # Ensure the directory exists
    mkdir -p "$STATE_DIR"
  '';
  
  programs.noctalia = {
    enable = true;

    settings = {

      bar.default = {
        center = [ "group:g1" ];
        end = [
          "media"
          "tray"
          "notifications"
          "clipboard"
          "network"
          "bluetooth"
          "spacer_2"
          "volume"
          "brightness"
          "battery"
          "spacer_2"
          "session"
        ];
        padding = 11;
        position = "left";
        shadow = false;
        start = [ "clock" "launcher" "workspaces" ];

        capsule_group = [
          {
            accordion = false;
            accordion_direction = "end";
            enabled = true;
            fill = "primary";
            id = "g1";
            members = [ "cpu" "ram" "temp" ];
            opacity = 0.10000000149011612;
            padding = 24.0;
            widget_spacing = 16;
          }
        ];
      };

      desktop_widgets = {
        enabled = false;
        schema_version = 2;
        widget_order = [ ];

        grid = {
          cell_size = 16;
          major_interval = 4;
          visible = true;
        };

        widget = { };
      };

      dock = {
        enabled = true;
        active_monitor_only = true;
        background_opacity = 0.9;
        cross_axis_padding = 0;
        icon_size = 20;
        item_spacing = 10;
        main_axis_padding = 8;
        reserve_space = false;
        shadow = false;
      };

      idle = {
        behavior_order = [ "lock" "screen-off" "lock-and-suspend" ];

        behavior = {
          lock = {
            action = "lock";
            enabled = true;
            timeout = 300.0;
          };

          lock-and-suspend = {
            action = "lock_and_suspend";
            enabled = true;
            timeout = 600.0;
          };

          screen-off = {
            action = "screen_off";
            enabled = true;
            timeout = 420.0;
          };
        };
      };

      location = {
        address = "Smlednik, Slovenia";
      };

      lockscreen = {
        blurred_desktop = true;
      };

      lockscreen_widgets = {
        enabled = false;
        schema_version = 2;
        widget_order = [
          "lockscreen-login-box@DP-9"
          "lockscreen-login-box@DP-6"
          "lockscreen-login-box@DP-7"
          "lockscreen-login-box@DP-5"
          "lockscreen-login-box@eDP-1"
        ];

        grid = {
          cell_size = 16;
          major_interval = 4;
          visible = true;
        };

        widget = {
          "lockscreen-login-box@DP-5" = {
            box_height = 196.0;
            box_width = 810.0;
            cx = 1280.0;
            cy = 898.0;
            output = "DP-5";
            rotation = 0.0;
            type = "login_box";

            settings = {
              background_color = "surface_variant";
              background_opacity = 0.88;
              background_radius = 12.0;
              center_password_text = false;
              input_opacity = 1.0;
              input_radius = 6.0;
              layout = "regular";
              show_caps_lock = true;
              show_keyboard_layout = true;
              show_login_button = true;
              show_media = true;
              show_session_buttons = true;
              show_unlock_hint = true;
              show_weather = true;
            };
          };

          "lockscreen-login-box@DP-6" = {
            box_height = 196.0;
            box_width = 810.0;
            cx = 1280.0;
            cy = 898.0;
            output = "DP-6";
            rotation = 0.0;
            type = "login_box";

            settings = {
              background_color = "surface_variant";
              background_opacity = 0.88;
              background_radius = 12.0;
              center_password_text = false;
              input_opacity = 1.0;
              input_radius = 6.0;
              layout = "regular";
              show_caps_lock = true;
              show_keyboard_layout = true;
              show_login_button = true;
              show_media = true;
              show_session_buttons = true;
              show_unlock_hint = true;
              show_weather = true;
            };
          };

          "lockscreen-login-box@DP-7" = {
            box_height = 196.0;
            box_width = 810.0;
            cx = 1280.0;
            cy = 898.0;
            output = "DP-7";
            rotation = 0.0;
            type = "login_box";

            settings = {
              background_color = "surface_variant";
              background_opacity = 0.88;
              background_radius = 12.0;
              center_password_text = false;
              input_opacity = 1.0;
              input_radius = 6.0;
              layout = "regular";
              show_caps_lock = true;
              show_keyboard_layout = true;
              show_login_button = true;
              show_media = true;
              show_session_buttons = true;
              show_unlock_hint = true;
              show_weather = true;
            };
          };

          "lockscreen-login-box@DP-9" = {
            box_height = 196.0;
            box_width = 810.0;
            cx = 1280.0;
            cy = 898.0;
            output = "DP-9";
            rotation = 0.0;
            type = "login_box";

            settings = {
              background_color = "surface_variant";
              background_opacity = 0.88;
              background_radius = 12.0;
              center_password_text = false;
              input_opacity = 1.0;
              input_radius = 6.0;
              layout = "regular";
              show_caps_lock = true;
              show_keyboard_layout = true;
              show_login_button = true;
              show_media = true;
              show_session_buttons = true;
              show_unlock_hint = true;
              show_weather = true;
            };
          };

          "lockscreen-login-box@eDP-1" = {
            box_height = 196.0;
            box_width = 810.0;
            cx = 960.0;
            cy = 1018.0;
            output = "eDP-1";
            rotation = 0.0;
            type = "login_box";

            settings = {
              background_color = "surface_variant";
              background_opacity = 0.88;
              background_radius = 12.0;
              center_password_text = false;
              input_opacity = 1.0;
              input_radius = 6.0;
              layout = "regular";
              show_caps_lock = true;
              show_keyboard_layout = true;
              show_login_button = true;
              show_media = true;
              show_session_buttons = true;
              show_unlock_hint = true;
              show_weather = true;
            };
          };
        };
      };

      nightlight = {
        enabled = true;
      };

      shell = {
        font_family = "DejaVu Sans";
        settings_show_advanced = false;

        launcher = {
          compact = false;
          categories = false;
        };

        panel = {
          open_near_click_session = true;
        };
      };

      theme = {
        source = "community";
        community_palette = "Breeze";
        mode = "dark";
      };

      plugins = {
        enabled = [
          "noctalia/screen_recorder"
        ];
      };

      wallpaper = {
        directory = "${config.home.homeDirectory}/nixos-config/wallpapers";

        default = {
          path = "${config.home.homeDirectory}/nixos-config/wallpapers/forest.png";
        };

        last = {
          path = "${config.home.homeDirectory}/nixos-config/wallpapers/forest.png";
        };

        monitors = {
          DP-5 = {
            path = "${config.home.homeDirectory}/nixos-config/wallpapers/forest.png";
          };

          DP-7 = {
            path = "${config.home.homeDirectory}/nixos-config/wallpapers/forest.png";
          };

          eDP-1 = {
            path = "${config.home.homeDirectory}/nixos-config/wallpapers/forest.png";
          };
        };
      };

      widget.battery = {
        capsule = false;
      };

      widget.brightness = {
        capsule = true;
      };

      widget.clipboard = {
        enabled = false;
      };

      widget.cpu = {
        label_show_units = false;
      };

      widget.network = {
        show_label = false;
      };

      widget.ram = {
        label_show_units = false;
        stat = "ram_pct";
      };

      widget.session = {
        capsule_opacity = 0.0;
        capsule_padding = 10;
        capsule = true;
      };

      widget.spacer_2 = {
        type = "spacer";
      };

      widget.sysmon = {
        label_show_units = false;
        show_glyph = false;
        show_value = false;
        stat = "cpu_temp";
        visualization = "graph";
      };

      widget.temp = {
        label_show_units = false;
      };

      widget.tray = {
        drawer = true;
        scale = 0.90000000000000013;
      };

      widget.volume = {
        capsule = true;
      };
    };
  };
}
