include:
  - ../../global-network.yml

services:
  music-assistant:
    image: ghcr.io/music-assistant/server:2.7.10
    container_name: ${SERVICE_NAME}-app
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    extends:
      file: ../../global-compose.yml
      service: web-base-exposed
    volumes:
      - ./app-data:/data/
    networks:
      ha-net:
      macvlan-10:                      # 8095 # web
        ipv4_address: ${MACVLAN_IPV4}  # 8097 # comms with speakers
        ipv6_address: ${MACVLAN_IPV6}  # 5353/udp # mdns
    labels:
      - traefik.http.services.mass-service.loadbalancer.server.url=http://${MACVLAN_IPV4}:${SERVICE_PORT}  # because host mode on macvlan
      - traefik.http.routers.${SERVICE_NAME}.service=mass-service
    healthcheck:
      test: [] # disabled because web server doesnt like it


# NOTE:
# Če spreminjas settings.json, prej ugasni container, da ti ne prepiše