include:
  - ../global-network.yml

services:
  trilium:
    image: triliumnext/trilium:v0.101.1
    container_name: ${SERVICE_NAME}-app
    environment:
      TRILIUM_DATA_DIR: ${TRILIUM_DATA_DIR}
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    extends:
      file: ../global-compose.yml
      service: web-base-exposed
    volumes:
      - ./app-data:${TRILIUM_DATA_DIR}
    user: ""  # overwrites base compose, the image support non-root container by passing env variables
    healthcheck:
      test: []  # healthcheck disabled because it does not allow to connect to itself from container for unknown reason