include:
  - ../global-network.yml

services:
  teslamate:
    image: teslamate/teslamate:3.0
    container_name: ${SERVICE_NAME}-app
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_HOST: teslamate-db
      MQTT_HOST: ${MQTT_HOST}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    extends:
      file: ../global-compose.yml
      service: base
    #ports:  # webui, uncomment if you need it, mostly useless after it is setup
    #  - 192.168.10.15:4000:4000
    networks: 
      - ha-net
      - tesla-net
    depends_on:
      - teslamate-db


  teslamate-db:
    image: postgres:16.13
    extends:
      file: ../global-compose.yml
      service: base-postgres
    volumes:
       - ./db-data:/data/postgres
    networks: 
      - tesla-net


  grafana-teslamate:
    image: teslamate/grafana:3.0.0
    container_name: ${SERVICE_NAME}-grafana
    environment:
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_HOST: teslamate-db
    extends:
      file: ../global-compose.yml
      service: web-base-internal
    volumes:
      - ./app-data:/var/lib/grafana
    networks: 
      - tesla-net
    depends_on:
      - teslamate-db


networks:
  tesla-net:
