include:
  - ../global-network.yml

services:
  unifi-app:
    image: lscr.io/linuxserver/unifi-network-application:10.1.85-ls118
    container_name: ${SERVICE_NAME}-app
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=${SERVICE_NAME}-db
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_AUTHSOURCE=${MONGO_AUTHSOURCE}
    extends:
      file: ../global-compose.yml
      service: web-base-internal
    volumes:
      - ./app-data:/config
    ports:
      - 192.168.10.15:3478:3478/udp # STUN
      - 192.168.10.15:8080:8080  # Port used for device and application communication.
    #  - 192.168.10.15:10001:10001/udp # Port used for device discovery.
    #  - 1900:1900/udp # Port used for "Make application discoverable on L2 network" in the UniFi Network settings.
    #  - 8843:8843 # Port used for application GUI/API as seen in a web browser
    #  - 8880:8880 # Port used for HTTP portal redirection.
    #  - 6789:6789 # Port used for UniFi mobile speed test.
    #  - 5514:5514/udp # Port used for remote syslog capture.
    networks:
      - unifi-net
    depends_on:
      - unifi-db
    labels:
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.scheme=https
      - traefik.http.routers.${SERVICE_NAME}.middlewares=unifiHeaders@file,internal-whitelist@file
    user: "" # overwrites base compose, the image support non-root container by default
    healthcheck:  # broken because listening on https
      test: []

  unifi-db:
    image: mongo:8
    container_name: ${SERVICE_NAME}-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    extends:
      file: ../global-compose.yml
      service: base
    volumes:
      - ./db-data:/data/db
    networks:
      - unifi-net


networks:  
  unifi-net: