include:
  - ../global-network.yml

services:
  broker_paperless:
    image: docker.io/library/redis:8
    container_name: ${SERVICE_NAME}-broker
    extends:
      file: ../global-compose.yml
      service: base
    volumes:
      - ./redis-data:/data
    networks:
      - paperless-net


  db_paperless:
    image: docker.io/library/postgres:15
    container_name: ${SERVICE_NAME}-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    extends:
      file: ../global-compose.yml
      service: base
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - paperless-net


  paperless_app:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.9
    container_name: ${SERVICE_NAME}_app
    environment:
      PAPERLESS_REDIS: redis://${SERVICE_NAME}-broker:6379
      PAPERLESS_DBHOST: ${SERVICE_NAME}-db
      USERMAP_UID: ${USERMAP_UID}
      USERMAP_GID: ${USERMAP_GID}
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
    extends:
      file: ../global-compose.yml
      service: web-base-exposed
    volumes:
      - ./app-data:/usr/src/paperless/data
      - ./app-media:/usr/src/paperless/media
      - /impo-data/paperless/archive:/usr/src/paperless/media/documents/archive
      - /impo-data/paperless/consume:/usr/src/paperless/consume
    networks:
      - paperless-net
    depends_on:
      - db_paperless
      - broker_paperless
    user: "" # overwrites base compose, the image support non-root container by default


  paper-llama:
    image: ghcr.io/tomasinjo/paper-llama:main
    container_name: paper-llama
    environment:
      - PAPERLESS_URL=${PAPERLESS_URL}
      - PAPERLESS_TOKEN=${PAPERLESS_TOKEN}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - SCAN_INTERVAL=${SCAN_INTERVAL}
      - OVERRIDE_EXISTING_TAGS=${OVERRIDE_EXISTING_TAGS}
      - LOG_LEVEL=${LOG_LEVEL}
      - OCR_SOURCE=${OCR_SOURCE}
      - LLM_OCR_SOURCE_PAGE_LIMIT=${LLM_OCR_SOURCE_PAGE_LIMIT}
    extends:
      file: ../global-compose.yml
      service: base
    volumes:
      - ./paperllama-data/prompt.txt:/app/prompt.txt:ro
    networks:
      - paperless-net
      - llm-net
    depends_on:
      - paperless_app
    command: ["python", "main.py", "--mode", "auto"]


networks:
  paperless-net: