include:
  - ../global-network.yml

services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: ${SERVICE_NAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    extends:
      file: ../global-compose.yml
      service: base
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - nextcloud-net
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW


  nextcloud-app:
    image: nextcloud
    container_name: ${SERVICE_NAME}-app
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${SERVICE_NAME}-db
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
    extends:
      file: ../global-compose.yml
      service: web-base-exposed
    volumes:
      - ./app-data:/var/www/html
      - /impo-data/nextcloud:/nc
      - /impo-data/paperless:/paperless
    networks:
      - nextcloud-net
    depends_on:
      - nextcloud-db
    labels:
      # SHARING GATEKEEPER WHITELIST ON SHARE VISIT
      - traefik.http.routers.nextcloud-share.rule=Host(`${SERVICE_FQDN}`) && PathRegexp(`^\/s\/(?:[A-Z,a-z,0-9]){15}$`)
      - traefik.http.routers.nextcloud-share.entrypoints=https,http
      - traefik.http.routers.nextcloud-share.tls=true
      - traefik.http.routers.nextcloud-share.tls.certresolver=fikus_resolver
      - traefik.http.routers.nextcloud-share.middlewares=gatekeeper_nextcloud_share@docker

networks:
  nextcloud-net: