include:
  - ../global-network.yml

services:
  victoriametrics:
    image: docker.io/victoriametrics/victoria-logs:v1.48.0
    container_name: ${SERVICE_NAME}-app
    extends:
      file: ../global-compose.yml
      service: web-base-internal
    volumes:
      - ./app-data:/victoria-logs-data
    ports:
      - '127.0.0.1:9428:9428'
    command: '-storageDataPath=victoria-logs-data'