include:
  - ../global-network.yml

services:
  traefik:
    image: traefik:v3.6.9
    container_name: ${SERVICE_NAME}-app
    extends:
      file: ../global-compose.yml
      service: base
    volumes:
      - ./app-data/:/etc/traefik/
      - ./app-plugins:/plugins-storage  # to set correct permissions. fails to write if non-root
    networks:
      traefik-net:
      dockerproxy-net:
      macvlan-10:
        ipv4_address: ${MACVLAN_IPV4}
        ipv6_address: ${MACVLAN_IPV6}
    depends_on:
      - dockerproxy
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0  # allows binding low ports


  dockerproxy:
    image: wollomatic/socket-proxy:1.11.3
    container_name: ${SERVICE_NAME}-dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net
      - dockerproxy-net
    command:
      - '-loglevel=info'
      - '-allowfrom=traefik'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)' # this regexp allows readonly access only for requests that traefik needs
      - '-allowHEAD=/_ping'
      - '-shutdowngracetime=5'
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:131 # 131 is docker gid
    restart: always

  gatekeeper:
    image: ghcr.io/tomasinjo/gatekeeper:main
    container_name: ${SERVICE_NAME}-gatekeeper
    environment:
      MAX_IP_LEN: ${MAX_IP_LEN}
      DEFAULT_SOURCE_RANGE: ${DEFAULT_SOURCE_RANGE}
    extends:
      file: ../global-compose.yml
      service: base
    volumes: 
      - ./app-data/file_providers/dynamic-whitelist.yml:/app/dynamic-whitelist.yml
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gatekeeper_immich_share.forwardauth.address=http://gatekeeper:5000/verify_share_request?protocol=http&container_name_port=immich-server:2283
      - traefik.http.middlewares.gatekeeper_immich_share.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.gatekeeper_nextcloud_share.forwardauth.address=http://gatekeeper:5000/verify_share_request?protocol=http&container_name_port=nextcloud-app:80
      - traefik.http.middlewares.gatekeeper_nextcloud_share.forwardauth.trustForwardHeader=true


networks:
  dockerproxy-net:
