# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "apex" "gasket" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.gasket
  ];
  #services.udev.extraRules = ''
  #  SUBSYSTEM=="apex", MODE="0660", GROUP="docker"
  #'';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/987089a7-616c-4e41-8727-9718ee05f247";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4480ec3a-7bd5-4d93-893f-bb87f0adc733";
      fsType = "ext4";
    };

  fileSystems."/games_mx500" =
    { device = "/dev/disk/by-uuid/c46b4975-2ad5-4fac-b52a-b60658e226d6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5EC9-C98D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/75f9bd43-0543-4262-9199-3a1d396273dc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
