include:
  - ../../global-network.yml

services:
  ollama:
    image: ollama/ollama:0.17.7
    container_name: ${SERVICE_NAME}-ollama
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      OLLAMA_DEBUG: 0
    extends:
      file: ../../global-compose.yml
      service: base-cuda
    volumes:
      - ./ollama-data:/root/.ollama
    ports:
      - 7869:11434
    networks:
      - llm-net
    user: "" # does not support non-root


  ollama-webui:
    image: ghcr.io/open-webui/open-webui:0.8-slim
    container_name: ${SERVICE_NAME}-app
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434
      ENV: prod
      WEBUI_AUTH: "True"
      WEBUI_NAME: ${WEBUI_NAME}
      WEBUI_URL: https://${SERVICE_FQDN}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    extends:
      file: ../../global-compose.yml
      service: web-base-exposed
    volumes:
      - ./app-data:/app/backend/data
    networks:
      - llm-net
    depends_on:
      - ollama
    user: ""  # does not support non-root