include:
  - ../../global-network.yml

services:
  pinchflat:
    image: keglin/pinchflat:latest
    container_name: ${SERVICE_NAME}-app
    environment:
      TZ: ${TZ}
      LOG_LEVEL: ${LOG_LEVEL}
    extends:
      file: ../../global-compose.yml
      service: web-base-internal
    volumes:
      - ./app-data:/config
      - ${PF_DOWNLOADS_PATH}:/downloads