include:
  - ../../global-network.yml

services:
  umami:
    image: ghcr.io/umami-software/umami:3.0.3
    container_name: ${SERVICE_NAME}-app
    environment:
      DATABASE_URL: ${DATABASE_TYPE}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${SERVICE_NAME}-db:5432/${POSTGRES_DB}
      APP_SECRET: ${APP_SECRET}
    extends:
      file: ../../global-compose.yml
      service: web-base-internal
    networks:
      - umami-net
    depends_on:
      - umami-db


  umami-db:
    image: postgres:16.13
    extends:
      file: ../../global-compose.yml
      service: base-postgres
    volumes:
       - ./db-data:/data/postgres
    networks:
      - umami-net

networks:
  umami-net: