include:
  - ../../global-network.yml

services: 
  appdaemon:
    image: acockburn/appdaemon:4.5.13
    container_name: ${SERVICE_NAME}-app
    environment:
      HA_URL: ${HA_URL}
      HA_KEY: ${HA_KEY}
      TZ: ${TZ}
    extends:
      file: ../../global-compose.yml
      service: web-base-internal
    volumes:
      - ./app-data:/conf
    networks:
      - ha-net
    cpuset: '12-19' # use only E-cores
    user: ""  # overrides base compose. can't run without root, fails at installing with pip