include:
  - ../global-network.yml

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.17.0
    container_name: ${SERVICE_NAME}-app
    environment: 
      FRIGATE_RTSP_USER: ${FRIGATE_RTSP_USER}
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      FRIGATE_MQTT_USER: ${FRIGATE_MQTT_USER}
      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
      FRIGATE_MEDIA_DIR: ${FRIGATE_MEDIA_DIR}
    extends:
      file: ../global-compose.yml
      service: web-base-internal-quicksync
    volumes:
      - ./app-data:/config
      - ${FRIGATE_MEDIA_DIR}:/media/frigate/

      # The following overrides are required to support running as a non-root user
      # s6 overrides
      - ./overrides/s6/log-prepare-run:/etc/s6-overlay/s6-rc.d/log-prepare/run
      - ./overrides/s6/nginx-check:/etc/s6-overlay/s6-rc.d/nginx/data/check
      - ./overrides/s6/s6-applyuidgid:/package/admin/s6/command/s6-applyuidgid

      # letsencrypt dirs need to exist so that we can provide certs or so that the container can generate self-signed certs and store them here
      - ./overrides/letsencrypt/live/frigate:/etc/letsencrypt/live/frigate
      - ./overrides/letsencrypt/www:/etc/letsencrypt/www
      
      # nginx overrides
      - ./overrides/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./overrides/nginx/conf/base_path.conf:/usr/local/nginx/conf/base_path.conf
      - ./overrides/nginx/conf/listen.conf:/usr/local/nginx/conf/listen.conf
      - ./overrides/nginx/logs:/usr/local/nginx/logs
      - ./overrides/nginx/temp_dirs:/usr/local/nginx/temp_dirs
    ports:
#      - 1935:1935 # RTMP feeds
      - 192.168.10.15:8555:8555
    networks:
      - ha-net
    cpuset: '12-19' # use only E-cores
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
    cap_add:
      - CAP_PERFMON
    tmpfs:
      # permissions don't seem to work properly using `shm_size`.
      - /dev/shm:mode=770,uid=1111,gid=1111,size=268435456 
      - /tmp/cache:mode=770,uid=1111,gid=1111,size=1G
    group_add:
      - 989 # coral group, made static in hardware.configuration.nix
    security_opt:
      - no-new-privileges:false # override the base compose - wont start without it, says it cant access /run.
