include:
  - ../../global-network.yml

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0.5236-ls137
    container_name: ${SERVICE_NAME}-app
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    extends:
      file: ../../global-compose.yml
      service: web-base-internal
    volumes:
      - ./app-data:/config
    networks:
      - arr-net
    user: ""  # overwrites base compose, the image support non-root container by default