include:
  - ../../global-network.yml

services:
  nocodb: 
    image: nocodb/nocodb:0.301.3
    container_name: ${SERVICE_NAME}-app
    environment: 
      NC_DB: pg://fafi_db:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}
      NC_PUBLIC_URL: https://${SERVICE_FQDN}
      NC_DISABLE_TELE: true
    extends:
      file: ../../global-compose.yml
      service: web-base-exposed
    networks: 
      - fafi-net
    volumes: 
      - ./app-data:/usr/app/data
    depends_on:
      - fafi_db


#  fafi_db:
#    container_name: fafi_db
#    image: postgres:16.12
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#      PGDATA: /data/postgres
#    extends:
#      file: ../../global-compose.yml
#      service: base
#    volumes:
#       - ./db-data:/data/postgres
#    ports:
#      - ${INTERFACE_IP}:4432:5432
#    networks: 
#      - fafi-net

  fafi_db:
    image: postgres:16.12
    container_name: fafi_db
    extends:
      file: ../../global-compose.yml
      service: base-postgres
    volumes:
       - ./db-data:/data/postgres
    ports:
      - ${INTERFACE_IP}:4432:5432
    networks: 
      - fafi-net
