x-cuda-mixin: &cuda-mixin
  deploy:
    resources:
      reservations:
        devices:
        - driver: cdi
          device_ids:
          - nvidia.com/gpu=all
          capabilities:
            - gpu

x-quicksync-mixin: &quicksync-mixin
  devices:
    - /dev/dri/renderD128:/dev/dri/renderD128
  group_add:
    - "303"


services:
  base:
    user: 1111:1111
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

  web-base:  # typically unused, use exposed or internal
    extends: { service: base }
    healthcheck:
      test:
        - CMD-SHELL
        - |
          if command -v curl >/dev/null; then
            curl -f http://localhost:${SERVICE_PORT} || exit 1;
          elif command -v wget >/dev/null; then
            wget --no-verbose --tries=1 --spider http://localhost:${SERVICE_PORT} || exit 1;
          else
            exit 1;
          fi
      interval: 1m
      timeout: 10s
    networks:
      - 'traefik-net'
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_FQDN}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=https,http
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_PORT}

  web-base-exposed:
    extends: { service: web-base }
    labels:
      - traefik.http.routers.${SERVICE_NAME}.middlewares=dynamic-whitelist@file
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=fikus_resolver

  web-base-internal:
    extends: { service: web-base }
    labels:
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=internal-whitelist@file"


  web-base-exposed-cuda:
    extends: { service: web-base-exposed }
    <<: *cuda-mixin

  web-base-internal-cuda:
    extends: { service: web-base-internal }
    <<: *cuda-mixin

  web-base-exposed-quicksync:
    extends: { service: web-base-exposed }
    <<: *quicksync-mixin

  web-base-internal-quicksync:
    extends: { service: web-base-internal }
    <<: *quicksync-mixin

  base-cuda:
    extends: { service: base }
    <<: *cuda-mixin

  base-quicksync:
    extends: { service: base }
    <<: *quicksync-mixin

