include:
  - ../../global-network.yml

services:
  ha:
    image: homeassistant/home-assistant:2026.3.1
    container_name: ${SERVICE_NAME}-app
    environment:
      PUID: ${PUID}
      GUID: ${GUID}
      TZ: ${TZ}
    extends:
      file: ../../global-compose.yml
      service: web-base
    volumes:
      - ./app-data:/config
      - ./app-media:/media
      - /dev/serial/by-id:/dev/serial/by-id  # for zigbee
    ports:
      - 192.168.10.15:5683:5683/udp  # shelly em3 CoIoT
    networks:
      - ha-net
    labels:
      - traefik.http.routers.${SERVICE_NAME}.service=ha_service@file
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=fikus_resolver
      - traefik.http.routers.${SERVICE_NAME}.tls.options=fikus_mtls@file
    user: ""  # override base compose, it is set by env vars
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # for zigbee
    cap_drop: []


  ha-db:
    image: postgres:16.12
    extends:
      file: ../../global-compose.yml
      service: base-postgres
    volumes:
       - ./db-data:/data/postgres
    networks:
      - ha-net


  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: ${SERVICE_NAME}-mqtt
    extends:
      file: ../../global-compose.yml
      service: base
    volumes:
      - ./mqtt-data/:/mosquitto/
    networks:
      - ha-net
    ports:
      - 192.168.10.15:1883:1883
